'use strict';
const HEADERS=['棟別','戶別','樓層','住戶','LINE 暱稱','LINE ID','車位','所有權人','職業領域','專長資源','Notes'];
const norm=s=>String(s??'').normalize('NFKC').toUpperCase().replace(/[‐‑–—－]/g,'-').replace(/\s/g,'');
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell!=='')throw Error('CSV 引號格式不正確');else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV 有未結束的引號');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(!rows.length)throw Error('檔案沒有資料');const headers=rows.shift().map(x=>x.trim());if(!['棟別','戶別','樓層'].every(x=>headers.includes(x)))throw Error('請匯出「住戶資料」分頁，第一列須包含棟別、戶別、樓層');if(new Set(headers).size!==headers.length)throw Error('欄位名稱重複');return rows.map((r,i)=>{if(r.length!==headers.length)throw Error(`第 ${i+2} 列欄位數不一致`);return Object.fromEntries(headers.map((h,j)=>[h,r[j].trim()]));}).filter(r=>HEADERS.slice(3).some(h=>r[h]));}
function unitKey(r){let u=norm(r['戶別']),b=norm(r['棟別']).replace(/棟$/,''),f=norm(r['樓層']).replace(/樓|F/g,'');if(/^[A-Z]+\d+-\d+$/.test(u))return u;if(!u)return '';if(!u.startsWith(b))u=b+u;return f?`${u}-${f}`:u;}
function parkingKeys(s){const text=norm(s).replace(/地下([1-9])樓?/g,'B$1').replace(/(B\d+)(?:樓|層|F)?[之_:：#號]*[-]?([0-9]+)/g,'$1-$2');return [...new Set(text.match(/B\d+-\d+/g)||[])];}
function names(rs,key){return [...new Set(rs.flatMap(r=>[r['住戶'],r['LINE 暱稱'],r['所有權人']]).filter(v=>v&&norm(v)!==norm(key)))];}
function floorOf(key){return key.match(/-(\d+)$/)?.[1]+'F';}
function labelSize(label,width){return Math.min(18,Math.max(1,(width-10)/[...label].reduce((n,c)=>n+(/[\x00-\x7F]/.test(c)?.65:1),0)));}

if(typeof module!=='undefined')module.exports={parseCSV,unitKey,parkingKeys,names,floorOf,labelSize};
if(typeof document!=='undefined'){
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',STORAGE='reading-taiwan-notebook-v1';
const RESIDENTIAL_FLOORS=Array.from({length:18},(_,i)=>(i+1)+'F');
const MAPPED_FLOORS=[...RESIDENTIAL_FLOORS,'B1','B2','B3'];
const sharedPlan=f=>/^\d+F$/.test(f)&&parseInt(f)>=5&&parseInt(f)<=18;
let rows=[],marks=[],floor='1F',zoom=1,selected=null,editing=null,draw=false,drag=null;
function defaults(){const out=[{id:'lobby',floor:'1F',label:'大廳',kind:'space',key:'',verified:true,box:[725,705,280,267]}];[[396,808,42,154],[441,808,45,154],[491,808,42,154],[536,808,39,154],[640,795,36,167],[681,795,41,167],[1009,790,44,172],[1058,795,39,167],[1159,793,39,169],[1203,793,40,169],[1248,786,85,188],[1340,786,83,188]].forEach((box,i)=>out.push({id:`shop${i}`,floor:'1F',label:`待核對 ${i+1}`,kind:'space',key:'',verified:false,box}));out.push(...(typeof RESIDENTIAL_MARKS!=='undefined'?RESIDENTIAL_MARKS.map(m=>({...m,box:[...m.box]})):[]));return out.concat(typeof BASEMENT_MARKS!=='undefined'?BASEMENT_MARKS.map(m=>({...m,box:[...m.box]})):[]);}
marks=defaults();
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function status(s){$('status').textContent=s;}
function snapshot(){return {version:1,mapRevision:6,exportedAt:new Date().toISOString(),rows:[],marks};}
function persist(){if($('remember').checked){try{localStorage.setItem(STORAGE,JSON.stringify(snapshot()));}catch{status('無法在此瀏覽器保存，請下載備份。');}}}
function validate(data){if(data?.version!==1||!Array.isArray(data.rows)||!Array.isArray(data.marks))throw Error('備份格式不正確');if(data.rows.length>50000||data.marks.length>5000)throw Error('備份超出筆數限制');for(const r of data.rows)if(!r||typeof r!=='object'||Array.isArray(r)||!Object.values(r).every(v=>typeof v==='string'))throw Error('住戶資料格式不正確');const ids=new Set();for(const m of data.marks){if(!m||typeof m.id!=='string'||ids.has(m.id)||!MAPPED_FLOORS.includes(m.floor)||!['unit','parking','space'].includes(m.kind)||typeof m.key!=='string'||typeof m.label!=='string'||typeof m.verified!=='boolean'||!Array.isArray(m.box)||m.box.length!==4||!m.box.every(Number.isFinite)||m.box[0]<0||m.box[1]<0||m.box[2]<=0||m.box[3]<=0||m.box[0]+m.box[2]>1889||m.box[1]+m.box[3]>1336)throw Error('位置資料格式不正確');ids.add(m.id);}return data;}
function upgradeMarks(data){const saved=data.marks,revision=data.mapRevision||0;if(revision>=6)return saved;const ids=new Set(saved.map(m=>m.id)),keys=new Set(saved.filter(m=>m.key).map(m=>m.kind+':'+norm(m.key)));return saved.concat(defaults().filter(m=>((revision<6&&m.floor==='B1')||(revision<2&&['B2','B3'].includes(m.floor))||(revision<3&&['2F','3F','4F'].includes(m.floor))||(revision<4&&m.floor==='5F')||(revision<5&&/^\d+F$/.test(m.floor)&&parseInt(m.floor)>=6&&parseInt(m.floor)<=18))&&!ids.has(m.id)&&(!m.key||!keys.has(m.kind+':'+norm(m.key)))));}

function groups(){const map=new Map();rows.forEach((r,i)=>{const k=unitKey(r)||`未填戶別・${i+1}`;if(!map.has(k))map.set(k,[]);map.get(k).push(r);});return map;}
function focusDetail(){if(!$('residentDialog').open)$('residentDialog').showModal();}
$('closeResident').onclick=()=>$('residentDialog').close();
function renderFloors(){const picker=$('floorPicker'),values=[...new Set([...RESIDENTIAL_FLOORS,...Array.from(groups().keys()).map(floorOf).filter(f=>/^\d+F$/.test(f))])].sort((a,b)=>parseInt(a)-parseInt(b));picker.replaceChildren();for(const f of values){const o=el('option',f+(MAPPED_FLOORS.includes(f)?' · 平面圖':' · 戶別列表'));o.value=f;picker.append(o);}for(const f of ['B1','B2','B3']){const o=el('option',f+' · 停車場');o.value=f;picker.append(o);}picker.value=values.includes(floor)||/^B[123]$/.test(floor)?floor:'1F';}
function renderFloorGrid(){const grid=$('floorGrid');grid.replaceChildren(el('h2',floor+' 住戶'),el('p','此樓層尚未加入平面圖。以下按戶別排列，不代表實際位置。'));const list=el('div',undefined,'unitGrid');for(const [key,rs] of groups()){if(floorOf(key)!==floor)continue;const b=el('button',key,'unitTile');b.append(el('small',names(rs,key).join('、')||'查看紀錄'));b.onclick=()=>{grid.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectUnit(key);};list.append(b);}grid.append(list);}
function renderResults(){renderFloors();if(!MAPPED_FLOORS.includes(floor))renderFloorGrid();const q=norm($('search').value),g=groups();$('stats').textContent=`${g.size} 戶 · ${rows.length} 筆紀錄 · ${marks.filter(m=>m.verified&&m.kind!=='space').length} 個已核對圖面標記`;$('results').replaceChildren();let count=0;for(const [key,rs] of g){if(q&&!norm(key+' '+rs.flatMap(Object.values).join(' ')).includes(q))continue;count++;const b=el('button',key,'result');b.append(el('small',names(rs,key).join('、')||`${rs.length} 筆紀錄`));b.onclick=()=>selectUnit(key);$('results').append(b);}if(!count)$('results').append(el('div',rows.length?'找不到符合的紀錄':'請按 Google 授權，載入最新住戶資料。','empty'));}
function renderMap(){const svg=$('overlay');svg.replaceChildren();for(const m of marks.filter(m=>m.floor===floor)){const g=document.createElementNS(NS,'g');g.setAttribute('class',`${m.verified?'':'pending'} ${selected===m.id?'selected':''}`);g.setAttribute('tabindex','0');g.setAttribute('role','button');g.setAttribute('aria-label',`${m.label}${m.verified?'':'，待核對'}`);const r=document.createElementNS(NS,'rect');['x','y','width','height'].forEach((k,i)=>r.setAttribute(k,m.box[i]));const t=document.createElementNS(NS,'text');t.setAttribute('x',m.box[0]+m.box[2]/2);t.setAttribute('y',m.box[1]+m.box[3]/2);t.setAttribute('text-anchor','middle');t.textContent=m.label;t.style.fontSize=labelSize(m.label,m.box[2])+'px';t.style.strokeWidth='2px';t.setAttribute('dominant-baseline','middle');const title=document.createElementNS(NS,'title');title.textContent=m.label+(m.key?' · '+m.key:'');g.append(title,r,t);g.onclick=()=>{if(!draw){selected=m.id;renderMap();showMark(m);}};g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selected=m.id;renderMap();showMark(m);}};svg.append(g);}$('mappingCount').textContent=`${floor} · ${marks.filter(m=>m.floor===floor).length} 個標記`;}
function displayRows(rs){for(const [index,r] of rs.entries()){const key=unitKey(r),title=names([r],key)[0]||`紀錄 ${index+1}`,block=el('div',undefined,'person');block.append(el('h3',title));const dl=el('dl'),seen=new Set([norm(title),norm(key)]);for(const [k,v] of Object.entries(r)){if(!v||['棟別','戶別','樓層'].includes(k)||(['住戶','LINE 暱稱','所有權人'].includes(k)&&norm(v)===norm(key)))continue;if(k==='住戶'&&seen.has(norm(v)))continue;if(k==='LINE 暱稱'&&norm(v)===norm(title))continue;dl.append(el('dt',k),el('dd',v));seen.add(norm(v));}block.append(dl);$('detail').append(block);}}
function showMark(m){focusDetail();const d=$('detail');d.replaceChildren(el('span',m.verified?'已核對':'待核對位置','tag'),el('h2',m.key||m.label));const edit=el('button','編輯 / 綁定位置');edit.onclick=()=>openEditor(m);d.append(edit);const rs=m.kind==='unit'?rows.filter(r=>unitKey(r)===norm(m.key)):m.kind==='parking'?rows.filter(r=>parkingKeys(r['車位']).includes(norm(m.key))):[];if(rs.length){if(!m.verified)d.append(el('p','資料已依代號連結，圖面位置仍待核對。'));const keys=[...new Set(rs.map(unitKey))];for(const key of keys){if(key!==m.key)d.append(el('h3',key));displayRows(rows.filter(r=>unitKey(r)===key));}}else d.append(el('p',m.kind==='space'?'此空間尚未綁定戶別，請按「編輯 / 綁定位置」指定；不會自動猜測住戶。':`目前資料中沒有符合 ${m.key} 的紀錄。請核對 CSV 的戶別／車位代號及樓層，或編輯此位置代號。`));}
function selectUnit(key){focusDetail();const rs=groups().get(key)||[],parks=rs.flatMap(r=>parkingKeys(r['車位'])),matches=marks.filter(m=>(m.kind==='unit'&&norm(m.key)===key)||(m.kind==='parking'&&parks.includes(norm(m.key))));$('detail').replaceChildren(el('span','住戶資料','tag'),el('h2',key));if(matches.length){for(const m of matches){const b=el('button',`定位 ${m.key}${m.verified?'':'（待核對）'}`);b.onclick=()=>{setFloor(m.floor);selected=m.id;renderMap();$('residentDialog').close();const scale=$('stage').clientWidth/1888;$('viewport').scrollTo({left:(m.box[0]+m.box[2]/2)*scale-$('viewport').clientWidth/2,top:(m.box[1]+m.box[3]/2)*scale-$('viewport').clientHeight/2,behavior:'smooth'});};$('detail').append(b);}}else $('detail').append(el('p','此戶尚未綁定目前的圖面位置，仍可在此查閱完整資料。'));displayRows(rs);}
function welcome(){$('residentDialog').close();$('results').hidden=false;$('backResults').hidden=true;$('detail').replaceChildren(el('span','你的私人社區筆記','tag'),el('h2','從一個位置，認識一位鄰居。'),el('p','按 Google 授權載入最新住戶資料後，即可搜尋住戶、車位或專長。'),el('p','2F～18F 已加入圖面及戶別標記；5F～18F 依建商相同格局沿用四樓底圖。一樓店舖尚待綁定戶別。B2 的 122–244 與 B3 的 1–121 已依原圖標記。B1 已補上原圖可辨識的汽車位；機車位尚未建立連結。'));}
function resize(){const width=Math.max(250,$('viewport').clientWidth)*zoom;$('stage').style.width=width+'px';}
function setFloor(f){if(draw)$('draw').click();floor=f;selected=null;const mapped=MAPPED_FLOORS.includes(f);$('viewport').hidden=!mapped;$('floorGrid').hidden=mapped;for(const id of ['minus','fit','plus','draw'])$(id).disabled=!mapped;$('floorPicker').value=f;if(mapped)$('plan').src=(sharedPlan(f)?'4f':f.toLowerCase())+'-source.jpg';$('plan').alt=sharedPlan(f)?f+' 共用格局底圖（原圖為四樓）':f==='1F'?'一樓原始平面圖':f+' 原始平面圖';$('maptitle').textContent=mapped?(f==='1F'?'一樓平面圖':f+(f.startsWith('B')?' 停車場平面圖':' 平面圖')):f+' 戶別列表';document.querySelectorAll('[data-floor]').forEach(b=>b.classList.toggle('active',b.dataset.floor===f));zoom=1;resize();$('viewport').scrollTo(0,0);renderMap();if(!mapped)renderFloorGrid();$('maphint').textContent=sharedPlan(f)?'依建商平面圖，4～18F 格局相同；此處沿用四樓底圖，戶別連結為 '+f+'。原圖露臺與約定專用註記仍屬四樓。':mapped?'點選標記查看資料；拖曳空白處移動。':'此頁是依 CSV 產生的戶別列表，尚非實際平面圖。';}
function openEditor(m){editing=m;$('maplabel').value=m.label;$('kind').value=m.kind;$('mapkey').value=m.key;$('verified').checked=m.verified;$('deleteMap').hidden=!marks.some(x=>x.id===m.id);$('editor').showModal();}
$('cancel').onclick=()=>$('editor').close();$('deleteMap').onclick=()=>{marks=marks.filter(m=>m.id!==editing.id);$('editor').close();selected=null;persist();renderMap();renderResults();welcome();};
$('mappingForm').onsubmit=e=>{e.preventDefault();const kind=$('kind').value,key=norm($('mapkey').value);if(kind==='unit'&&(!/^[A-Z]+\d+-\d+$/.test(key)||floorOf(key)!==floor)){alert('戶別代號須與目前樓層一致，例如 A1-'+parseInt(floor)+'（棟別＋戶別－樓層）。');return;}if(kind==='parking'&&(!/^B[123]-\d+$/.test(key)||!key.startsWith(floor+'-'))){alert('車位代號須與目前樓層一致，例如 '+floor+'-123。');return;}if((!floor.startsWith('B')&&kind==='parking')||(/^B[123]$/.test(floor)&&kind==='unit')){alert('地上樓層請綁定戶別；地下室請綁定車位。');return;}const m={...editing,label:$('maplabel').value.trim()||key,kind,key:kind==='space'?'':key,verified:$('verified').checked};const i=marks.findIndex(x=>x.id===m.id);if(i<0)marks.push(m);else marks[i]=m;$('editor').close();selected=m.id;persist();renderMap();renderResults();showMark(m);status('位置已更新，請下載備份以保留對應關係。');};
function point(e){const r=$('stage').getBoundingClientRect();return [Math.max(0,Math.min(1888,(e.clientX-r.left)/r.width*1888)),Math.max(0,Math.min(1335,(e.clientY-r.top)/r.height*1335))];}
$('draw').onclick=()=>{draw=!draw;$('draw').classList.toggle('active',draw);$('viewport').style.cursor=draw?'crosshair':'grab';$('maphint').textContent=draw?'在圖面拖曳框選範圍，放開後設定戶別或車位。':'拖曳移動圖面，點選標記查看資料。';};
$('viewport').onpointerdown=e=>{if(e.button!==0)return;drag={start:point(e),x:e.clientX,y:e.clientY,left:$('viewport').scrollLeft,top:$('viewport').scrollTop,moved:false};if(draw){e.preventDefault();$('viewport').setPointerCapture(e.pointerId);}else if(!e.target.closest('g'))$('viewport').setPointerCapture(e.pointerId);};
$('viewport').onpointermove=e=>{if(!drag)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5)drag.moved=true;if(draw){const p=point(e);let r=$('draft');if(!r){r=document.createElementNS(NS,'rect');r.id='draft';$('overlay').append(r);}const b=[Math.min(p[0],drag.start[0]),Math.min(p[1],drag.start[1]),Math.abs(p[0]-drag.start[0]),Math.abs(p[1]-drag.start[1])];['x','y','width','height'].forEach((k,i)=>r.setAttribute(k,b[i]));}else if(drag.moved){$('viewport').scrollLeft=drag.left-e.clientX+drag.x;$('viewport').scrollTop=drag.top-e.clientY+drag.y;}};
$('viewport').onpointerup=e=>{if(!drag)return;const start=drag.start;drag=null;if(draw){const p=point(e);$('draft')?.remove();const box=[Math.min(p[0],start[0]),Math.min(p[1],start[1]),Math.abs(p[0]-start[0]),Math.abs(p[1]-start[1])];if(box[2]>8&&box[3]>8){$('draw').click();openEditor({id:'m'+Date.now(),floor,label:'新位置',kind:floor.startsWith('B')?'parking':'unit',key:'',verified:false,box});}}};$('viewport').onpointercancel=()=>{drag=null;$('draft')?.remove();};
document.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>setFloor(b.dataset.floor));$('plus').onclick=()=>{zoom=Math.min(5,zoom*1.3);resize();};$('minus').onclick=()=>{zoom=Math.max(.6,zoom/1.3);resize();};$('fit').onclick=()=>{zoom=1;resize();$('viewport').scrollTo(0,0);};window.addEventListener('resize',resize);$('search').oninput=()=>{$('results').hidden=false;$('backResults').hidden=true;renderResults();};$('backResults').onclick=()=>{$('results').hidden=false;$('backResults').hidden=true;};$('floorPicker').onchange=()=>setFloor($('floorPicker').value);
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>20e6)throw Error('檔案大於 20 MB');const text=await file.text();if(file.name.toLowerCase().endsWith('.json')){const data=validate(JSON.parse(text));if(!confirm('備份會取代目前的住戶資料與位置設定，是否繼續？'))return;rows=[];marks=upgradeMarks(data);}else{const parsed=parseCSV(text);if(rows.length&&!confirm('匯入 CSV 會取代目前住戶資料，位置設定會保留。是否繼續？'))return;rows=parsed;}selected=null;persist();renderResults();renderMap();welcome();status(`已匯入 ${rows.length} 筆紀錄。資料未上傳；請下載備份保留。`);}catch(e){status('匯入失敗：'+e.message);}finally{$('file').value='';}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=`閱讀台灣-私人備份-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('備份只包含位置設定，不含住戶資料。');};
$('remember').onchange=()=>{if($('remember').checked){persist();status('只保存位置設定，不保存住戶資料。');}else{try{localStorage.removeItem(STORAGE);}catch{}status('已關閉瀏覽器保存。目前畫面資料仍保留至關閉頁面。');}};
$('clear').onclick=()=>{if(!confirm('清除目前與此瀏覽器保存的住戶資料？圖面標記會保留，已下載的備份不會刪除。'))return;rows=[];try{localStorage.removeItem(STORAGE);}catch{}persist();renderResults();welcome();status('住戶資料已清除，位置標記保留。');};
try{const saved=localStorage.getItem(STORAGE);if(saved){const data=validate(JSON.parse(saved));rows=[];marks=upgradeMarks(data);$('remember').checked=true;persist();status('已載入位置設定，請重新授權載入住戶資料。');}}catch{status('未能讀取瀏覽器保存的資料，可重新匯入備份。');}
window.residentData={
 clear(){rows=[];selected=null;$('search').value='';renderResults();renderMap();welcome();},
 load(text){rows=parseCSV(text);selected=null;renderResults();renderMap();welcome();return rows.length;},
 status
};
window.addEventListener('pagehide',()=>window.residentData.clear());
resize();renderMap();renderResults();welcome();
}
